### ISSUE TITLE
Configure for all repos?

### ISSUE THREAD

**Issue by dave-green-uk** [lolcommits/lolcommits-slack#4]
Is there any means to configure the plugin globally rather than having to run the config step for every project?

**Comment by matthutchinson** [comment]
We've had [this request](https://github.com/mroth/lolcommits/issues/306) for a long time on the regular lolcommits repo.. but no feature built yet.  

This [wiki page](https://github.com/mroth/lolcommits/wiki/Enabling-Lolcommits-for-all-your-Git-Repositories) explains how you can use git templates to enable lolcommits automatically for all repos, but each repo will still need its own config.
